ALTER TABLE [dbo].[tbl_SimSoDep_DauSoChiTiet]
    ADD CONSTRAINT [PK_DauSoChiTiet] PRIMARY KEY CLUSTERED ([MaDauSoChiTiet] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

