ALTER TABLE [dbo].[tbl_SimSoDep_DauSo]
    ADD CONSTRAINT [PK_DauSo] PRIMARY KEY CLUSTERED ([MaDauSo] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

