ALTER TABLE [dbo].[tbl_SimSoDep_LoaiGia]
    ADD CONSTRAINT [PK_LoaiGia] PRIMARY KEY CLUSTERED ([MaLoaiGia] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

