ALTER TABLE [dbo].[tbl_SimSoDep_LoaiDoDaiSo]
    ADD CONSTRAINT [PK_LoaiDoDaiSo] PRIMARY KEY CLUSTERED ([MaLoaiDoDai] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

