ALTER TABLE [dbo].[tbl_SimSoDep_NhaMang]
    ADD CONSTRAINT [PK_NhaMang] PRIMARY KEY CLUSTERED ([MaNhaMang] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

