ALTER TABLE [dbo].[tbl_SimSoDep_BanMenh]
    ADD CONSTRAINT [PK_tbl_SimSoDep_BanMenh] PRIMARY KEY CLUSTERED ([IdBanMenh] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

