ALTER TABLE [dbo].[tbl_SimSoDep_TinhThanh]
    ADD CONSTRAINT [PK_TinhThanh] PRIMARY KEY CLUSTERED ([MaTinhThanh] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

