ALTER TABLE [dbo].[tbl_SimSoDep_DaiLy]
    ADD CONSTRAINT [PK_tbl_SimSoDep_DaiLy] PRIMARY KEY CLUSTERED ([MaDaiLy] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

