//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace SimSoDepStore
{
    public partial class tbl_SimSoDep_LoaiSimChiTietSimSo
    {
        #region Primitive Properties
    
        public virtual int MaLoaiSimChiTiet
        {
            get { return _maLoaiSimChiTiet; }
            set
            {
                if (_maLoaiSimChiTiet != value)
                {
                    if (tbl_SimSoDep_LoaiSimChiTiet != null && tbl_SimSoDep_LoaiSimChiTiet.MaLoaiSimChiTiet != value)
                    {
                        tbl_SimSoDep_LoaiSimChiTiet = null;
                    }
                    _maLoaiSimChiTiet = value;
                }
            }
        }
        private int _maLoaiSimChiTiet;
    
        public virtual long MaSoDienThoai
        {
            get { return _maSoDienThoai; }
            set
            {
                if (_maSoDienThoai != value)
                {
                    if (tbl_SimSoDep_SimSo != null && tbl_SimSoDep_SimSo.MaSoDienThoai != value)
                    {
                        tbl_SimSoDep_SimSo = null;
                    }
                    _maSoDienThoai = value;
                }
            }
        }
        private long _maSoDienThoai;
    
        public virtual Nullable<System.DateTime> CreateDate
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual tbl_SimSoDep_LoaiSimChiTiet tbl_SimSoDep_LoaiSimChiTiet
        {
            get { return _tbl_SimSoDep_LoaiSimChiTiet; }
            set
            {
                if (!ReferenceEquals(_tbl_SimSoDep_LoaiSimChiTiet, value))
                {
                    var previousValue = _tbl_SimSoDep_LoaiSimChiTiet;
                    _tbl_SimSoDep_LoaiSimChiTiet = value;
                    Fixuptbl_SimSoDep_LoaiSimChiTiet(previousValue);
                }
            }
        }
        private tbl_SimSoDep_LoaiSimChiTiet _tbl_SimSoDep_LoaiSimChiTiet;
    
        public virtual tbl_SimSoDep_SimSo tbl_SimSoDep_SimSo
        {
            get { return _tbl_SimSoDep_SimSo; }
            set
            {
                if (!ReferenceEquals(_tbl_SimSoDep_SimSo, value))
                {
                    var previousValue = _tbl_SimSoDep_SimSo;
                    _tbl_SimSoDep_SimSo = value;
                    Fixuptbl_SimSoDep_SimSo(previousValue);
                }
            }
        }
        private tbl_SimSoDep_SimSo _tbl_SimSoDep_SimSo;

        #endregion
        #region Association Fixup
    
        private void Fixuptbl_SimSoDep_LoaiSimChiTiet(tbl_SimSoDep_LoaiSimChiTiet previousValue)
        {
            if (previousValue != null && previousValue.tbl_SimSoDep_LoaiSimChiTietSimSo.Contains(this))
            {
                previousValue.tbl_SimSoDep_LoaiSimChiTietSimSo.Remove(this);
            }
    
            if (tbl_SimSoDep_LoaiSimChiTiet != null)
            {
                if (!tbl_SimSoDep_LoaiSimChiTiet.tbl_SimSoDep_LoaiSimChiTietSimSo.Contains(this))
                {
                    tbl_SimSoDep_LoaiSimChiTiet.tbl_SimSoDep_LoaiSimChiTietSimSo.Add(this);
                }
                if (MaLoaiSimChiTiet != tbl_SimSoDep_LoaiSimChiTiet.MaLoaiSimChiTiet)
                {
                    MaLoaiSimChiTiet = tbl_SimSoDep_LoaiSimChiTiet.MaLoaiSimChiTiet;
                }
            }
        }
    
        private void Fixuptbl_SimSoDep_SimSo(tbl_SimSoDep_SimSo previousValue)
        {
            if (previousValue != null && previousValue.tbl_SimSoDep_LoaiSimChiTietSimSo.Contains(this))
            {
                previousValue.tbl_SimSoDep_LoaiSimChiTietSimSo.Remove(this);
            }
    
            if (tbl_SimSoDep_SimSo != null)
            {
                if (!tbl_SimSoDep_SimSo.tbl_SimSoDep_LoaiSimChiTietSimSo.Contains(this))
                {
                    tbl_SimSoDep_SimSo.tbl_SimSoDep_LoaiSimChiTietSimSo.Add(this);
                }
                if (MaSoDienThoai != tbl_SimSoDep_SimSo.MaSoDienThoai)
                {
                    MaSoDienThoai = tbl_SimSoDep_SimSo.MaSoDienThoai;
                }
            }
        }

        #endregion
    }
}
