//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace SimSoDepStore
{
    public partial class tbl_SimSoDep_LoaiSim
    {
        #region Primitive Properties
    
        public virtual int MaLoaiSim
        {
            get;
            set;
        }
    
        public virtual string TenLoaiSim
        {
            get;
            set;
        }
    
        public virtual string MoTa
        {
            get;
            set;
        }
    
        public virtual string Alias
        {
            get;
            set;
        }
    
        public virtual string EnumFixed
        {
            get;
            set;
        }
    
        public virtual Nullable<int> Status
        {
            get;
            set;
        }
    
        public virtual Nullable<int> SapXep
        {
            get;
            set;
        }
    
        public virtual string MetaDescription
        {
            get;
            set;
        }
    
        public virtual string MetaKeyword
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<tbl_SimSoDep_LoaiSimChiTiet> tbl_SimSoDep_LoaiSimChiTiet
        {
            get
            {
                if (_tbl_SimSoDep_LoaiSimChiTiet == null)
                {
                    var newCollection = new FixupCollection<tbl_SimSoDep_LoaiSimChiTiet>();
                    newCollection.CollectionChanged += Fixuptbl_SimSoDep_LoaiSimChiTiet;
                    _tbl_SimSoDep_LoaiSimChiTiet = newCollection;
                }
                return _tbl_SimSoDep_LoaiSimChiTiet;
            }
            set
            {
                if (!ReferenceEquals(_tbl_SimSoDep_LoaiSimChiTiet, value))
                {
                    var previousValue = _tbl_SimSoDep_LoaiSimChiTiet as FixupCollection<tbl_SimSoDep_LoaiSimChiTiet>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= Fixuptbl_SimSoDep_LoaiSimChiTiet;
                    }
                    _tbl_SimSoDep_LoaiSimChiTiet = value;
                    var newValue = value as FixupCollection<tbl_SimSoDep_LoaiSimChiTiet>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += Fixuptbl_SimSoDep_LoaiSimChiTiet;
                    }
                }
            }
        }
        private ICollection<tbl_SimSoDep_LoaiSimChiTiet> _tbl_SimSoDep_LoaiSimChiTiet;
    
        public virtual ICollection<tbl_SimSoDep_SimSoLoaiSim> tbl_SimSoDep_SimSoLoaiSim
        {
            get
            {
                if (_tbl_SimSoDep_SimSoLoaiSim == null)
                {
                    var newCollection = new FixupCollection<tbl_SimSoDep_SimSoLoaiSim>();
                    newCollection.CollectionChanged += Fixuptbl_SimSoDep_SimSoLoaiSim;
                    _tbl_SimSoDep_SimSoLoaiSim = newCollection;
                }
                return _tbl_SimSoDep_SimSoLoaiSim;
            }
            set
            {
                if (!ReferenceEquals(_tbl_SimSoDep_SimSoLoaiSim, value))
                {
                    var previousValue = _tbl_SimSoDep_SimSoLoaiSim as FixupCollection<tbl_SimSoDep_SimSoLoaiSim>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= Fixuptbl_SimSoDep_SimSoLoaiSim;
                    }
                    _tbl_SimSoDep_SimSoLoaiSim = value;
                    var newValue = value as FixupCollection<tbl_SimSoDep_SimSoLoaiSim>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += Fixuptbl_SimSoDep_SimSoLoaiSim;
                    }
                }
            }
        }
        private ICollection<tbl_SimSoDep_SimSoLoaiSim> _tbl_SimSoDep_SimSoLoaiSim;

        #endregion
        #region Association Fixup
    
        private void Fixuptbl_SimSoDep_LoaiSimChiTiet(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (tbl_SimSoDep_LoaiSimChiTiet item in e.NewItems)
                {
                    item.tbl_SimSoDep_LoaiSim = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (tbl_SimSoDep_LoaiSimChiTiet item in e.OldItems)
                {
                    if (ReferenceEquals(item.tbl_SimSoDep_LoaiSim, this))
                    {
                        item.tbl_SimSoDep_LoaiSim = null;
                    }
                }
            }
        }
    
        private void Fixuptbl_SimSoDep_SimSoLoaiSim(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (tbl_SimSoDep_SimSoLoaiSim item in e.NewItems)
                {
                    item.tbl_SimSoDep_LoaiSim = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (tbl_SimSoDep_SimSoLoaiSim item in e.OldItems)
                {
                    if (ReferenceEquals(item.tbl_SimSoDep_LoaiSim, this))
                    {
                        item.tbl_SimSoDep_LoaiSim = null;
                    }
                }
            }
        }

        #endregion
    }
}
