//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace SimSoDepStore
{
    public partial class tbl_SimSoDep_KinhDich
    {
        #region Primitive Properties
    
        public virtual int IdQueThuong
        {
            get { return _idQueThuong; }
            set
            {
                if (_idQueThuong != value)
                {
                    if (tbl_SimSoDep_BatQuai1 != null && tbl_SimSoDep_BatQuai1.IdQueBatQuai != value)
                    {
                        tbl_SimSoDep_BatQuai1 = null;
                    }
                    _idQueThuong = value;
                }
            }
        }
        private int _idQueThuong;
    
        public virtual int IdQueHa
        {
            get { return _idQueHa; }
            set
            {
                if (_idQueHa != value)
                {
                    if (tbl_SimSoDep_BatQuai != null && tbl_SimSoDep_BatQuai.IdQueBatQuai != value)
                    {
                        tbl_SimSoDep_BatQuai = null;
                    }
                    _idQueHa = value;
                }
            }
        }
        private int _idQueHa;
    
        public virtual string TenQue
        {
            get;
            set;
        }
    
        public virtual string PhienAm
        {
            get;
            set;
        }
    
        public virtual string LoiDich
        {
            get;
            set;
        }
    
        public virtual string YNghia
        {
            get;
            set;
        }
    
        public virtual string HinhQue
        {
            get;
            set;
        }
    
        public virtual int IdKinhDich
        {
            get;
            set;
        }
    
        public virtual Nullable<int> LoaiQue
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual tbl_SimSoDep_BatQuai tbl_SimSoDep_BatQuai
        {
            get { return _tbl_SimSoDep_BatQuai; }
            set
            {
                if (!ReferenceEquals(_tbl_SimSoDep_BatQuai, value))
                {
                    var previousValue = _tbl_SimSoDep_BatQuai;
                    _tbl_SimSoDep_BatQuai = value;
                    Fixuptbl_SimSoDep_BatQuai(previousValue);
                }
            }
        }
        private tbl_SimSoDep_BatQuai _tbl_SimSoDep_BatQuai;
    
        public virtual tbl_SimSoDep_BatQuai tbl_SimSoDep_BatQuai1
        {
            get { return _tbl_SimSoDep_BatQuai1; }
            set
            {
                if (!ReferenceEquals(_tbl_SimSoDep_BatQuai1, value))
                {
                    var previousValue = _tbl_SimSoDep_BatQuai1;
                    _tbl_SimSoDep_BatQuai1 = value;
                    Fixuptbl_SimSoDep_BatQuai1(previousValue);
                }
            }
        }
        private tbl_SimSoDep_BatQuai _tbl_SimSoDep_BatQuai1;
    
        public virtual ICollection<tbl_SimSoDep_SimSo> tbl_SimSoDep_SimSo
        {
            get
            {
                if (_tbl_SimSoDep_SimSo == null)
                {
                    var newCollection = new FixupCollection<tbl_SimSoDep_SimSo>();
                    newCollection.CollectionChanged += Fixuptbl_SimSoDep_SimSo;
                    _tbl_SimSoDep_SimSo = newCollection;
                }
                return _tbl_SimSoDep_SimSo;
            }
            set
            {
                if (!ReferenceEquals(_tbl_SimSoDep_SimSo, value))
                {
                    var previousValue = _tbl_SimSoDep_SimSo as FixupCollection<tbl_SimSoDep_SimSo>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= Fixuptbl_SimSoDep_SimSo;
                    }
                    _tbl_SimSoDep_SimSo = value;
                    var newValue = value as FixupCollection<tbl_SimSoDep_SimSo>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += Fixuptbl_SimSoDep_SimSo;
                    }
                }
            }
        }
        private ICollection<tbl_SimSoDep_SimSo> _tbl_SimSoDep_SimSo;

        #endregion
        #region Association Fixup
    
        private void Fixuptbl_SimSoDep_BatQuai(tbl_SimSoDep_BatQuai previousValue)
        {
            if (previousValue != null && previousValue.tbl_SimSoDep_KinhDich.Contains(this))
            {
                previousValue.tbl_SimSoDep_KinhDich.Remove(this);
            }
    
            if (tbl_SimSoDep_BatQuai != null)
            {
                if (!tbl_SimSoDep_BatQuai.tbl_SimSoDep_KinhDich.Contains(this))
                {
                    tbl_SimSoDep_BatQuai.tbl_SimSoDep_KinhDich.Add(this);
                }
                if (IdQueHa != tbl_SimSoDep_BatQuai.IdQueBatQuai)
                {
                    IdQueHa = tbl_SimSoDep_BatQuai.IdQueBatQuai;
                }
            }
        }
    
        private void Fixuptbl_SimSoDep_BatQuai1(tbl_SimSoDep_BatQuai previousValue)
        {
            if (previousValue != null && previousValue.tbl_SimSoDep_KinhDich1.Contains(this))
            {
                previousValue.tbl_SimSoDep_KinhDich1.Remove(this);
            }
    
            if (tbl_SimSoDep_BatQuai1 != null)
            {
                if (!tbl_SimSoDep_BatQuai1.tbl_SimSoDep_KinhDich1.Contains(this))
                {
                    tbl_SimSoDep_BatQuai1.tbl_SimSoDep_KinhDich1.Add(this);
                }
                if (IdQueThuong != tbl_SimSoDep_BatQuai1.IdQueBatQuai)
                {
                    IdQueThuong = tbl_SimSoDep_BatQuai1.IdQueBatQuai;
                }
            }
        }
    
        private void Fixuptbl_SimSoDep_SimSo(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (tbl_SimSoDep_SimSo item in e.NewItems)
                {
                    item.tbl_SimSoDep_KinhDich = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (tbl_SimSoDep_SimSo item in e.OldItems)
                {
                    if (ReferenceEquals(item.tbl_SimSoDep_KinhDich, this))
                    {
                        item.tbl_SimSoDep_KinhDich = null;
                    }
                }
            }
        }

        #endregion
    }
}
