//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace SimSoDepStore
{
    public partial class tbl_SimSoDep_KhachHang
    {
        #region Primitive Properties
    
        public virtual int MaKhachHang
        {
            get;
            set;
        }
    
        public virtual string TenKhachHang
        {
            get;
            set;
        }
    
        public virtual string DiaChi
        {
            get;
            set;
        }
    
        public virtual string SoDienThoai
        {
            get;
            set;
        }
    
        public virtual string Email
        {
            get;
            set;
        }
    
        public virtual Nullable<int> MaTinhThanh
        {
            get { return _maTinhThanh; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_maTinhThanh != value)
                    {
                        if (tbl_SimSoDep_TinhThanh != null && tbl_SimSoDep_TinhThanh.MaTinhThanh != value)
                        {
                            tbl_SimSoDep_TinhThanh = null;
                        }
                        _maTinhThanh = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<int> _maTinhThanh;
    
        public virtual string GhiChu
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<tbl_SimSoDep_DatHang> tbl_SimSoDep_DatHang
        {
            get
            {
                if (_tbl_SimSoDep_DatHang == null)
                {
                    var newCollection = new FixupCollection<tbl_SimSoDep_DatHang>();
                    newCollection.CollectionChanged += Fixuptbl_SimSoDep_DatHang;
                    _tbl_SimSoDep_DatHang = newCollection;
                }
                return _tbl_SimSoDep_DatHang;
            }
            set
            {
                if (!ReferenceEquals(_tbl_SimSoDep_DatHang, value))
                {
                    var previousValue = _tbl_SimSoDep_DatHang as FixupCollection<tbl_SimSoDep_DatHang>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= Fixuptbl_SimSoDep_DatHang;
                    }
                    _tbl_SimSoDep_DatHang = value;
                    var newValue = value as FixupCollection<tbl_SimSoDep_DatHang>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += Fixuptbl_SimSoDep_DatHang;
                    }
                }
            }
        }
        private ICollection<tbl_SimSoDep_DatHang> _tbl_SimSoDep_DatHang;
    
        public virtual tbl_SimSoDep_TinhThanh tbl_SimSoDep_TinhThanh
        {
            get { return _tbl_SimSoDep_TinhThanh; }
            set
            {
                if (!ReferenceEquals(_tbl_SimSoDep_TinhThanh, value))
                {
                    var previousValue = _tbl_SimSoDep_TinhThanh;
                    _tbl_SimSoDep_TinhThanh = value;
                    Fixuptbl_SimSoDep_TinhThanh(previousValue);
                }
            }
        }
        private tbl_SimSoDep_TinhThanh _tbl_SimSoDep_TinhThanh;

        #endregion
        #region Association Fixup
    
        private bool _settingFK = false;
    
        private void Fixuptbl_SimSoDep_TinhThanh(tbl_SimSoDep_TinhThanh previousValue)
        {
            if (previousValue != null && previousValue.tbl_SimSoDep_KhachHang.Contains(this))
            {
                previousValue.tbl_SimSoDep_KhachHang.Remove(this);
            }
    
            if (tbl_SimSoDep_TinhThanh != null)
            {
                if (!tbl_SimSoDep_TinhThanh.tbl_SimSoDep_KhachHang.Contains(this))
                {
                    tbl_SimSoDep_TinhThanh.tbl_SimSoDep_KhachHang.Add(this);
                }
                if (MaTinhThanh != tbl_SimSoDep_TinhThanh.MaTinhThanh)
                {
                    MaTinhThanh = tbl_SimSoDep_TinhThanh.MaTinhThanh;
                }
            }
            else if (!_settingFK)
            {
                MaTinhThanh = null;
            }
        }
    
        private void Fixuptbl_SimSoDep_DatHang(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (tbl_SimSoDep_DatHang item in e.NewItems)
                {
                    item.tbl_SimSoDep_KhachHang = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (tbl_SimSoDep_DatHang item in e.OldItems)
                {
                    if (ReferenceEquals(item.tbl_SimSoDep_KhachHang, this))
                    {
                        item.tbl_SimSoDep_KhachHang = null;
                    }
                }
            }
        }

        #endregion
    }
}
