//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace SimSoDepStore
{
    public partial class tbl_SimSoDep_NguHanh
    {
        #region Primitive Properties
    
        public virtual int IdNguHanh
        {
            get;
            set;
        }
    
        public virtual string Ten
        {
            get;
            set;
        }
    
        public virtual Nullable<int> TuongSinh
        {
            get { return _tuongSinh; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_tuongSinh != value)
                    {
                        if (tbl_SimSoDep_NguHanh2 != null && tbl_SimSoDep_NguHanh2.IdNguHanh != value)
                        {
                            tbl_SimSoDep_NguHanh2 = null;
                        }
                        _tuongSinh = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<int> _tuongSinh;
    
        public virtual Nullable<int> TuongKhac
        {
            get { return _tuongKhac; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_tuongKhac != value)
                    {
                        if (tbl_SimSoDep_NguHanh3 != null && tbl_SimSoDep_NguHanh3.IdNguHanh != value)
                        {
                            tbl_SimSoDep_NguHanh3 = null;
                        }
                        _tuongKhac = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<int> _tuongKhac;
    
        public virtual string MoTa
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<tbl_SimSoDep_NguHanh> tbl_SimSoDep_NguHanh1
        {
            get
            {
                if (_tbl_SimSoDep_NguHanh1 == null)
                {
                    var newCollection = new FixupCollection<tbl_SimSoDep_NguHanh>();
                    newCollection.CollectionChanged += Fixuptbl_SimSoDep_NguHanh1;
                    _tbl_SimSoDep_NguHanh1 = newCollection;
                }
                return _tbl_SimSoDep_NguHanh1;
            }
            set
            {
                if (!ReferenceEquals(_tbl_SimSoDep_NguHanh1, value))
                {
                    var previousValue = _tbl_SimSoDep_NguHanh1 as FixupCollection<tbl_SimSoDep_NguHanh>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= Fixuptbl_SimSoDep_NguHanh1;
                    }
                    _tbl_SimSoDep_NguHanh1 = value;
                    var newValue = value as FixupCollection<tbl_SimSoDep_NguHanh>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += Fixuptbl_SimSoDep_NguHanh1;
                    }
                }
            }
        }
        private ICollection<tbl_SimSoDep_NguHanh> _tbl_SimSoDep_NguHanh1;
    
        public virtual tbl_SimSoDep_NguHanh tbl_SimSoDep_NguHanh2
        {
            get { return _tbl_SimSoDep_NguHanh2; }
            set
            {
                if (!ReferenceEquals(_tbl_SimSoDep_NguHanh2, value))
                {
                    var previousValue = _tbl_SimSoDep_NguHanh2;
                    _tbl_SimSoDep_NguHanh2 = value;
                    Fixuptbl_SimSoDep_NguHanh2(previousValue);
                }
            }
        }
        private tbl_SimSoDep_NguHanh _tbl_SimSoDep_NguHanh2;
    
        public virtual ICollection<tbl_SimSoDep_NguHanh> tbl_SimSoDep_NguHanh11
        {
            get
            {
                if (_tbl_SimSoDep_NguHanh11 == null)
                {
                    var newCollection = new FixupCollection<tbl_SimSoDep_NguHanh>();
                    newCollection.CollectionChanged += Fixuptbl_SimSoDep_NguHanh11;
                    _tbl_SimSoDep_NguHanh11 = newCollection;
                }
                return _tbl_SimSoDep_NguHanh11;
            }
            set
            {
                if (!ReferenceEquals(_tbl_SimSoDep_NguHanh11, value))
                {
                    var previousValue = _tbl_SimSoDep_NguHanh11 as FixupCollection<tbl_SimSoDep_NguHanh>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= Fixuptbl_SimSoDep_NguHanh11;
                    }
                    _tbl_SimSoDep_NguHanh11 = value;
                    var newValue = value as FixupCollection<tbl_SimSoDep_NguHanh>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += Fixuptbl_SimSoDep_NguHanh11;
                    }
                }
            }
        }
        private ICollection<tbl_SimSoDep_NguHanh> _tbl_SimSoDep_NguHanh11;
    
        public virtual tbl_SimSoDep_NguHanh tbl_SimSoDep_NguHanh3
        {
            get { return _tbl_SimSoDep_NguHanh3; }
            set
            {
                if (!ReferenceEquals(_tbl_SimSoDep_NguHanh3, value))
                {
                    var previousValue = _tbl_SimSoDep_NguHanh3;
                    _tbl_SimSoDep_NguHanh3 = value;
                    Fixuptbl_SimSoDep_NguHanh3(previousValue);
                }
            }
        }
        private tbl_SimSoDep_NguHanh _tbl_SimSoDep_NguHanh3;
    
        public virtual ICollection<tbl_SimSoDep_BanMenh> tbl_SimSoDep_BanMenh
        {
            get
            {
                if (_tbl_SimSoDep_BanMenh == null)
                {
                    var newCollection = new FixupCollection<tbl_SimSoDep_BanMenh>();
                    newCollection.CollectionChanged += Fixuptbl_SimSoDep_BanMenh;
                    _tbl_SimSoDep_BanMenh = newCollection;
                }
                return _tbl_SimSoDep_BanMenh;
            }
            set
            {
                if (!ReferenceEquals(_tbl_SimSoDep_BanMenh, value))
                {
                    var previousValue = _tbl_SimSoDep_BanMenh as FixupCollection<tbl_SimSoDep_BanMenh>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= Fixuptbl_SimSoDep_BanMenh;
                    }
                    _tbl_SimSoDep_BanMenh = value;
                    var newValue = value as FixupCollection<tbl_SimSoDep_BanMenh>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += Fixuptbl_SimSoDep_BanMenh;
                    }
                }
            }
        }
        private ICollection<tbl_SimSoDep_BanMenh> _tbl_SimSoDep_BanMenh;
    
        public virtual ICollection<tbl_SimSoDep_SimSo> tbl_SimSoDep_SimSo
        {
            get
            {
                if (_tbl_SimSoDep_SimSo == null)
                {
                    var newCollection = new FixupCollection<tbl_SimSoDep_SimSo>();
                    newCollection.CollectionChanged += Fixuptbl_SimSoDep_SimSo;
                    _tbl_SimSoDep_SimSo = newCollection;
                }
                return _tbl_SimSoDep_SimSo;
            }
            set
            {
                if (!ReferenceEquals(_tbl_SimSoDep_SimSo, value))
                {
                    var previousValue = _tbl_SimSoDep_SimSo as FixupCollection<tbl_SimSoDep_SimSo>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= Fixuptbl_SimSoDep_SimSo;
                    }
                    _tbl_SimSoDep_SimSo = value;
                    var newValue = value as FixupCollection<tbl_SimSoDep_SimSo>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += Fixuptbl_SimSoDep_SimSo;
                    }
                }
            }
        }
        private ICollection<tbl_SimSoDep_SimSo> _tbl_SimSoDep_SimSo;

        #endregion
        #region Association Fixup
    
        private bool _settingFK = false;
    
        private void Fixuptbl_SimSoDep_NguHanh2(tbl_SimSoDep_NguHanh previousValue)
        {
            if (previousValue != null && previousValue.tbl_SimSoDep_NguHanh1.Contains(this))
            {
                previousValue.tbl_SimSoDep_NguHanh1.Remove(this);
            }
    
            if (tbl_SimSoDep_NguHanh2 != null)
            {
                if (!tbl_SimSoDep_NguHanh2.tbl_SimSoDep_NguHanh1.Contains(this))
                {
                    tbl_SimSoDep_NguHanh2.tbl_SimSoDep_NguHanh1.Add(this);
                }
                if (TuongSinh != tbl_SimSoDep_NguHanh2.IdNguHanh)
                {
                    TuongSinh = tbl_SimSoDep_NguHanh2.IdNguHanh;
                }
            }
            else if (!_settingFK)
            {
                TuongSinh = null;
            }
        }
    
        private void Fixuptbl_SimSoDep_NguHanh3(tbl_SimSoDep_NguHanh previousValue)
        {
            if (previousValue != null && previousValue.tbl_SimSoDep_NguHanh11.Contains(this))
            {
                previousValue.tbl_SimSoDep_NguHanh11.Remove(this);
            }
    
            if (tbl_SimSoDep_NguHanh3 != null)
            {
                if (!tbl_SimSoDep_NguHanh3.tbl_SimSoDep_NguHanh11.Contains(this))
                {
                    tbl_SimSoDep_NguHanh3.tbl_SimSoDep_NguHanh11.Add(this);
                }
                if (TuongKhac != tbl_SimSoDep_NguHanh3.IdNguHanh)
                {
                    TuongKhac = tbl_SimSoDep_NguHanh3.IdNguHanh;
                }
            }
            else if (!_settingFK)
            {
                TuongKhac = null;
            }
        }
    
        private void Fixuptbl_SimSoDep_NguHanh1(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (tbl_SimSoDep_NguHanh item in e.NewItems)
                {
                    item.tbl_SimSoDep_NguHanh2 = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (tbl_SimSoDep_NguHanh item in e.OldItems)
                {
                    if (ReferenceEquals(item.tbl_SimSoDep_NguHanh2, this))
                    {
                        item.tbl_SimSoDep_NguHanh2 = null;
                    }
                }
            }
        }
    
        private void Fixuptbl_SimSoDep_NguHanh11(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (tbl_SimSoDep_NguHanh item in e.NewItems)
                {
                    item.tbl_SimSoDep_NguHanh3 = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (tbl_SimSoDep_NguHanh item in e.OldItems)
                {
                    if (ReferenceEquals(item.tbl_SimSoDep_NguHanh3, this))
                    {
                        item.tbl_SimSoDep_NguHanh3 = null;
                    }
                }
            }
        }
    
        private void Fixuptbl_SimSoDep_BanMenh(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (tbl_SimSoDep_BanMenh item in e.NewItems)
                {
                    item.tbl_SimSoDep_NguHanh = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (tbl_SimSoDep_BanMenh item in e.OldItems)
                {
                    if (ReferenceEquals(item.tbl_SimSoDep_NguHanh, this))
                    {
                        item.tbl_SimSoDep_NguHanh = null;
                    }
                }
            }
        }
    
        private void Fixuptbl_SimSoDep_SimSo(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (tbl_SimSoDep_SimSo item in e.NewItems)
                {
                    item.tbl_SimSoDep_NguHanh = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (tbl_SimSoDep_SimSo item in e.OldItems)
                {
                    if (ReferenceEquals(item.tbl_SimSoDep_NguHanh, this))
                    {
                        item.tbl_SimSoDep_NguHanh = null;
                    }
                }
            }
        }

        #endregion
    }
}
