//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace SimSoDepStore
{
    public partial class tbl_SimSoDep_DatHang
    {
        #region Primitive Properties
    
        public virtual int MaDatHang
        {
            get;
            set;
        }
    
        public virtual int MaKhachHang
        {
            get { return _maKhachHang; }
            set
            {
                if (_maKhachHang != value)
                {
                    if (tbl_SimSoDep_KhachHang != null && tbl_SimSoDep_KhachHang.MaKhachHang != value)
                    {
                        tbl_SimSoDep_KhachHang = null;
                    }
                    _maKhachHang = value;
                }
            }
        }
        private int _maKhachHang;
    
        public virtual long MaSoDienThoai
        {
            get { return _maSoDienThoai; }
            set
            {
                if (_maSoDienThoai != value)
                {
                    if (tbl_SimSoDep_SimSo != null && tbl_SimSoDep_SimSo.MaSoDienThoai != value)
                    {
                        tbl_SimSoDep_SimSo = null;
                    }
                    _maSoDienThoai = value;
                }
            }
        }
        private long _maSoDienThoai;
    
        public virtual Nullable<System.DateTime> ThoiGian
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual tbl_SimSoDep_KhachHang tbl_SimSoDep_KhachHang
        {
            get { return _tbl_SimSoDep_KhachHang; }
            set
            {
                if (!ReferenceEquals(_tbl_SimSoDep_KhachHang, value))
                {
                    var previousValue = _tbl_SimSoDep_KhachHang;
                    _tbl_SimSoDep_KhachHang = value;
                    Fixuptbl_SimSoDep_KhachHang(previousValue);
                }
            }
        }
        private tbl_SimSoDep_KhachHang _tbl_SimSoDep_KhachHang;
    
        public virtual tbl_SimSoDep_SimSo tbl_SimSoDep_SimSo
        {
            get { return _tbl_SimSoDep_SimSo; }
            set
            {
                if (!ReferenceEquals(_tbl_SimSoDep_SimSo, value))
                {
                    var previousValue = _tbl_SimSoDep_SimSo;
                    _tbl_SimSoDep_SimSo = value;
                    Fixuptbl_SimSoDep_SimSo(previousValue);
                }
            }
        }
        private tbl_SimSoDep_SimSo _tbl_SimSoDep_SimSo;

        #endregion
        #region Association Fixup
    
        private void Fixuptbl_SimSoDep_KhachHang(tbl_SimSoDep_KhachHang previousValue)
        {
            if (previousValue != null && previousValue.tbl_SimSoDep_DatHang.Contains(this))
            {
                previousValue.tbl_SimSoDep_DatHang.Remove(this);
            }
    
            if (tbl_SimSoDep_KhachHang != null)
            {
                if (!tbl_SimSoDep_KhachHang.tbl_SimSoDep_DatHang.Contains(this))
                {
                    tbl_SimSoDep_KhachHang.tbl_SimSoDep_DatHang.Add(this);
                }
                if (MaKhachHang != tbl_SimSoDep_KhachHang.MaKhachHang)
                {
                    MaKhachHang = tbl_SimSoDep_KhachHang.MaKhachHang;
                }
            }
        }
    
        private void Fixuptbl_SimSoDep_SimSo(tbl_SimSoDep_SimSo previousValue)
        {
            if (previousValue != null && previousValue.tbl_SimSoDep_DatHang.Contains(this))
            {
                previousValue.tbl_SimSoDep_DatHang.Remove(this);
            }
    
            if (tbl_SimSoDep_SimSo != null)
            {
                if (!tbl_SimSoDep_SimSo.tbl_SimSoDep_DatHang.Contains(this))
                {
                    tbl_SimSoDep_SimSo.tbl_SimSoDep_DatHang.Add(this);
                }
                if (MaSoDienThoai != tbl_SimSoDep_SimSo.MaSoDienThoai)
                {
                    MaSoDienThoai = tbl_SimSoDep_SimSo.MaSoDienThoai;
                }
            }
        }

        #endregion
    }
}
