//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace SimSoDepStore
{
    public partial class tbl_SimSoDep_DaiLy
    {
        #region Primitive Properties
    
        public virtual int MaDaiLy
        {
            get;
            set;
        }
    
        public virtual string TenDaiLy
        {
            get;
            set;
        }
    
        public virtual string DiDong
        {
            get;
            set;
        }
    
        public virtual string MayBan
        {
            get;
            set;
        }
    
        public virtual string DiaChi
        {
            get;
            set;
        }
    
        public virtual string Email
        {
            get;
            set;
        }
    
        public virtual Nullable<int> MaTinhThanh
        {
            get { return _maTinhThanh; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_maTinhThanh != value)
                    {
                        if (tbl_SimSoDep_TinhThanh != null && tbl_SimSoDep_TinhThanh.MaTinhThanh != value)
                        {
                            tbl_SimSoDep_TinhThanh = null;
                        }
                        _maTinhThanh = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<int> _maTinhThanh;

        #endregion
        #region Navigation Properties
    
        public virtual tbl_SimSoDep_TinhThanh tbl_SimSoDep_TinhThanh
        {
            get { return _tbl_SimSoDep_TinhThanh; }
            set
            {
                if (!ReferenceEquals(_tbl_SimSoDep_TinhThanh, value))
                {
                    var previousValue = _tbl_SimSoDep_TinhThanh;
                    _tbl_SimSoDep_TinhThanh = value;
                    Fixuptbl_SimSoDep_TinhThanh(previousValue);
                }
            }
        }
        private tbl_SimSoDep_TinhThanh _tbl_SimSoDep_TinhThanh;
    
        public virtual ICollection<tbl_SimSoDep_DaiLyTrietKhau> tbl_SimSoDep_DaiLyTrietKhau
        {
            get
            {
                if (_tbl_SimSoDep_DaiLyTrietKhau == null)
                {
                    var newCollection = new FixupCollection<tbl_SimSoDep_DaiLyTrietKhau>();
                    newCollection.CollectionChanged += Fixuptbl_SimSoDep_DaiLyTrietKhau;
                    _tbl_SimSoDep_DaiLyTrietKhau = newCollection;
                }
                return _tbl_SimSoDep_DaiLyTrietKhau;
            }
            set
            {
                if (!ReferenceEquals(_tbl_SimSoDep_DaiLyTrietKhau, value))
                {
                    var previousValue = _tbl_SimSoDep_DaiLyTrietKhau as FixupCollection<tbl_SimSoDep_DaiLyTrietKhau>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= Fixuptbl_SimSoDep_DaiLyTrietKhau;
                    }
                    _tbl_SimSoDep_DaiLyTrietKhau = value;
                    var newValue = value as FixupCollection<tbl_SimSoDep_DaiLyTrietKhau>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += Fixuptbl_SimSoDep_DaiLyTrietKhau;
                    }
                }
            }
        }
        private ICollection<tbl_SimSoDep_DaiLyTrietKhau> _tbl_SimSoDep_DaiLyTrietKhau;
    
        public virtual ICollection<tbl_SimSoDep_SimSo> tbl_SimSoDep_SimSo
        {
            get
            {
                if (_tbl_SimSoDep_SimSo == null)
                {
                    var newCollection = new FixupCollection<tbl_SimSoDep_SimSo>();
                    newCollection.CollectionChanged += Fixuptbl_SimSoDep_SimSo;
                    _tbl_SimSoDep_SimSo = newCollection;
                }
                return _tbl_SimSoDep_SimSo;
            }
            set
            {
                if (!ReferenceEquals(_tbl_SimSoDep_SimSo, value))
                {
                    var previousValue = _tbl_SimSoDep_SimSo as FixupCollection<tbl_SimSoDep_SimSo>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= Fixuptbl_SimSoDep_SimSo;
                    }
                    _tbl_SimSoDep_SimSo = value;
                    var newValue = value as FixupCollection<tbl_SimSoDep_SimSo>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += Fixuptbl_SimSoDep_SimSo;
                    }
                }
            }
        }
        private ICollection<tbl_SimSoDep_SimSo> _tbl_SimSoDep_SimSo;
    
        public virtual ICollection<tbl_SimSoDep_TangThem> tbl_SimSoDep_TangThem
        {
            get
            {
                if (_tbl_SimSoDep_TangThem == null)
                {
                    var newCollection = new FixupCollection<tbl_SimSoDep_TangThem>();
                    newCollection.CollectionChanged += Fixuptbl_SimSoDep_TangThem;
                    _tbl_SimSoDep_TangThem = newCollection;
                }
                return _tbl_SimSoDep_TangThem;
            }
            set
            {
                if (!ReferenceEquals(_tbl_SimSoDep_TangThem, value))
                {
                    var previousValue = _tbl_SimSoDep_TangThem as FixupCollection<tbl_SimSoDep_TangThem>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= Fixuptbl_SimSoDep_TangThem;
                    }
                    _tbl_SimSoDep_TangThem = value;
                    var newValue = value as FixupCollection<tbl_SimSoDep_TangThem>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += Fixuptbl_SimSoDep_TangThem;
                    }
                }
            }
        }
        private ICollection<tbl_SimSoDep_TangThem> _tbl_SimSoDep_TangThem;

        #endregion
        #region Association Fixup
    
        private bool _settingFK = false;
    
        private void Fixuptbl_SimSoDep_TinhThanh(tbl_SimSoDep_TinhThanh previousValue)
        {
            if (previousValue != null && previousValue.tbl_SimSoDep_DaiLy.Contains(this))
            {
                previousValue.tbl_SimSoDep_DaiLy.Remove(this);
            }
    
            if (tbl_SimSoDep_TinhThanh != null)
            {
                if (!tbl_SimSoDep_TinhThanh.tbl_SimSoDep_DaiLy.Contains(this))
                {
                    tbl_SimSoDep_TinhThanh.tbl_SimSoDep_DaiLy.Add(this);
                }
                if (MaTinhThanh != tbl_SimSoDep_TinhThanh.MaTinhThanh)
                {
                    MaTinhThanh = tbl_SimSoDep_TinhThanh.MaTinhThanh;
                }
            }
            else if (!_settingFK)
            {
                MaTinhThanh = null;
            }
        }
    
        private void Fixuptbl_SimSoDep_DaiLyTrietKhau(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (tbl_SimSoDep_DaiLyTrietKhau item in e.NewItems)
                {
                    item.tbl_SimSoDep_DaiLy = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (tbl_SimSoDep_DaiLyTrietKhau item in e.OldItems)
                {
                    if (ReferenceEquals(item.tbl_SimSoDep_DaiLy, this))
                    {
                        item.tbl_SimSoDep_DaiLy = null;
                    }
                }
            }
        }
    
        private void Fixuptbl_SimSoDep_SimSo(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (tbl_SimSoDep_SimSo item in e.NewItems)
                {
                    item.tbl_SimSoDep_DaiLy = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (tbl_SimSoDep_SimSo item in e.OldItems)
                {
                    if (ReferenceEquals(item.tbl_SimSoDep_DaiLy, this))
                    {
                        item.tbl_SimSoDep_DaiLy = null;
                    }
                }
            }
        }
    
        private void Fixuptbl_SimSoDep_TangThem(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (tbl_SimSoDep_TangThem item in e.NewItems)
                {
                    item.tbl_SimSoDep_DaiLy = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (tbl_SimSoDep_TangThem item in e.OldItems)
                {
                    if (ReferenceEquals(item.tbl_SimSoDep_DaiLy, this))
                    {
                        item.tbl_SimSoDep_DaiLy = null;
                    }
                }
            }
        }

        #endregion
    }
}
