//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace SimSoDepStore
{
    public partial class tbl_SimSoDep_LoaiSimChiTiet
    {
        #region Primitive Properties
    
        public virtual int MaLoaiSimChiTiet
        {
            get;
            set;
        }
    
        public virtual int MaLoaiSim
        {
            get { return _maLoaiSim; }
            set
            {
                if (_maLoaiSim != value)
                {
                    if (tbl_SimSoDep_LoaiSim != null && tbl_SimSoDep_LoaiSim.MaLoaiSim != value)
                    {
                        tbl_SimSoDep_LoaiSim = null;
                    }
                    _maLoaiSim = value;
                }
            }
        }
        private int _maLoaiSim;
    
        public virtual string TenLoaiSimChiTiet
        {
            get;
            set;
        }
    
        public virtual string MoTa
        {
            get;
            set;
        }
    
        public virtual string Alias
        {
            get;
            set;
        }
    
        public virtual string EnumFixed
        {
            get;
            set;
        }
    
        public virtual Nullable<int> SapXep
        {
            get;
            set;
        }
    
        public virtual Nullable<int> Status
        {
            get;
            set;
        }
    
        public virtual string MetaDescription
        {
            get;
            set;
        }
    
        public virtual string MetaKeyword
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual tbl_SimSoDep_LoaiSim tbl_SimSoDep_LoaiSim
        {
            get { return _tbl_SimSoDep_LoaiSim; }
            set
            {
                if (!ReferenceEquals(_tbl_SimSoDep_LoaiSim, value))
                {
                    var previousValue = _tbl_SimSoDep_LoaiSim;
                    _tbl_SimSoDep_LoaiSim = value;
                    Fixuptbl_SimSoDep_LoaiSim(previousValue);
                }
            }
        }
        private tbl_SimSoDep_LoaiSim _tbl_SimSoDep_LoaiSim;
    
        public virtual ICollection<tbl_SimSoDep_LoaiSimChiTietSimSo> tbl_SimSoDep_LoaiSimChiTietSimSo
        {
            get
            {
                if (_tbl_SimSoDep_LoaiSimChiTietSimSo == null)
                {
                    var newCollection = new FixupCollection<tbl_SimSoDep_LoaiSimChiTietSimSo>();
                    newCollection.CollectionChanged += Fixuptbl_SimSoDep_LoaiSimChiTietSimSo;
                    _tbl_SimSoDep_LoaiSimChiTietSimSo = newCollection;
                }
                return _tbl_SimSoDep_LoaiSimChiTietSimSo;
            }
            set
            {
                if (!ReferenceEquals(_tbl_SimSoDep_LoaiSimChiTietSimSo, value))
                {
                    var previousValue = _tbl_SimSoDep_LoaiSimChiTietSimSo as FixupCollection<tbl_SimSoDep_LoaiSimChiTietSimSo>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= Fixuptbl_SimSoDep_LoaiSimChiTietSimSo;
                    }
                    _tbl_SimSoDep_LoaiSimChiTietSimSo = value;
                    var newValue = value as FixupCollection<tbl_SimSoDep_LoaiSimChiTietSimSo>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += Fixuptbl_SimSoDep_LoaiSimChiTietSimSo;
                    }
                }
            }
        }
        private ICollection<tbl_SimSoDep_LoaiSimChiTietSimSo> _tbl_SimSoDep_LoaiSimChiTietSimSo;

        #endregion
        #region Association Fixup
    
        private void Fixuptbl_SimSoDep_LoaiSim(tbl_SimSoDep_LoaiSim previousValue)
        {
            if (previousValue != null && previousValue.tbl_SimSoDep_LoaiSimChiTiet.Contains(this))
            {
                previousValue.tbl_SimSoDep_LoaiSimChiTiet.Remove(this);
            }
    
            if (tbl_SimSoDep_LoaiSim != null)
            {
                if (!tbl_SimSoDep_LoaiSim.tbl_SimSoDep_LoaiSimChiTiet.Contains(this))
                {
                    tbl_SimSoDep_LoaiSim.tbl_SimSoDep_LoaiSimChiTiet.Add(this);
                }
                if (MaLoaiSim != tbl_SimSoDep_LoaiSim.MaLoaiSim)
                {
                    MaLoaiSim = tbl_SimSoDep_LoaiSim.MaLoaiSim;
                }
            }
        }
    
        private void Fixuptbl_SimSoDep_LoaiSimChiTietSimSo(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (tbl_SimSoDep_LoaiSimChiTietSimSo item in e.NewItems)
                {
                    item.tbl_SimSoDep_LoaiSimChiTiet = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (tbl_SimSoDep_LoaiSimChiTietSimSo item in e.OldItems)
                {
                    if (ReferenceEquals(item.tbl_SimSoDep_LoaiSimChiTiet, this))
                    {
                        item.tbl_SimSoDep_LoaiSimChiTiet = null;
                    }
                }
            }
        }

        #endregion
    }
}
