//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace SimSoDepStore
{
    public partial class tbl_SimSoDep_BatQuai
    {
        #region Primitive Properties
    
        public virtual int IdQueBatQuai
        {
            get;
            set;
        }
    
        public virtual string TenQue
        {
            get;
            set;
        }
    
        public virtual string HinhQue
        {
            get;
            set;
        }
    
        public virtual string PhienAm
        {
            get;
            set;
        }
    
        public virtual string MoTa
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<tbl_SimSoDep_KinhDich> tbl_SimSoDep_KinhDich
        {
            get
            {
                if (_tbl_SimSoDep_KinhDich == null)
                {
                    var newCollection = new FixupCollection<tbl_SimSoDep_KinhDich>();
                    newCollection.CollectionChanged += Fixuptbl_SimSoDep_KinhDich;
                    _tbl_SimSoDep_KinhDich = newCollection;
                }
                return _tbl_SimSoDep_KinhDich;
            }
            set
            {
                if (!ReferenceEquals(_tbl_SimSoDep_KinhDich, value))
                {
                    var previousValue = _tbl_SimSoDep_KinhDich as FixupCollection<tbl_SimSoDep_KinhDich>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= Fixuptbl_SimSoDep_KinhDich;
                    }
                    _tbl_SimSoDep_KinhDich = value;
                    var newValue = value as FixupCollection<tbl_SimSoDep_KinhDich>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += Fixuptbl_SimSoDep_KinhDich;
                    }
                }
            }
        }
        private ICollection<tbl_SimSoDep_KinhDich> _tbl_SimSoDep_KinhDich;
    
        public virtual ICollection<tbl_SimSoDep_KinhDich> tbl_SimSoDep_KinhDich1
        {
            get
            {
                if (_tbl_SimSoDep_KinhDich1 == null)
                {
                    var newCollection = new FixupCollection<tbl_SimSoDep_KinhDich>();
                    newCollection.CollectionChanged += Fixuptbl_SimSoDep_KinhDich1;
                    _tbl_SimSoDep_KinhDich1 = newCollection;
                }
                return _tbl_SimSoDep_KinhDich1;
            }
            set
            {
                if (!ReferenceEquals(_tbl_SimSoDep_KinhDich1, value))
                {
                    var previousValue = _tbl_SimSoDep_KinhDich1 as FixupCollection<tbl_SimSoDep_KinhDich>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= Fixuptbl_SimSoDep_KinhDich1;
                    }
                    _tbl_SimSoDep_KinhDich1 = value;
                    var newValue = value as FixupCollection<tbl_SimSoDep_KinhDich>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += Fixuptbl_SimSoDep_KinhDich1;
                    }
                }
            }
        }
        private ICollection<tbl_SimSoDep_KinhDich> _tbl_SimSoDep_KinhDich1;

        #endregion
        #region Association Fixup
    
        private void Fixuptbl_SimSoDep_KinhDich(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (tbl_SimSoDep_KinhDich item in e.NewItems)
                {
                    item.tbl_SimSoDep_BatQuai = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (tbl_SimSoDep_KinhDich item in e.OldItems)
                {
                    if (ReferenceEquals(item.tbl_SimSoDep_BatQuai, this))
                    {
                        item.tbl_SimSoDep_BatQuai = null;
                    }
                }
            }
        }
    
        private void Fixuptbl_SimSoDep_KinhDich1(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (tbl_SimSoDep_KinhDich item in e.NewItems)
                {
                    item.tbl_SimSoDep_BatQuai1 = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (tbl_SimSoDep_KinhDich item in e.OldItems)
                {
                    if (ReferenceEquals(item.tbl_SimSoDep_BatQuai1, this))
                    {
                        item.tbl_SimSoDep_BatQuai1 = null;
                    }
                }
            }
        }

        #endregion
    }
}
