//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace SimSoDepStore
{
    public partial class tbl_SimSoDep_BanMenh
    {
        #region Primitive Properties
    
        public virtual int IdBanMenh
        {
            get;
            set;
        }
    
        public virtual int Nam
        {
            get;
            set;
        }
    
        public virtual int IdNguHanh
        {
            get { return _idNguHanh; }
            set
            {
                if (_idNguHanh != value)
                {
                    if (tbl_SimSoDep_NguHanh != null && tbl_SimSoDep_NguHanh.IdNguHanh != value)
                    {
                        tbl_SimSoDep_NguHanh = null;
                    }
                    _idNguHanh = value;
                }
            }
        }
        private int _idNguHanh;
    
        public virtual string TenBanMenh
        {
            get;
            set;
        }
    
        public virtual string MoTa
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual tbl_SimSoDep_NguHanh tbl_SimSoDep_NguHanh
        {
            get { return _tbl_SimSoDep_NguHanh; }
            set
            {
                if (!ReferenceEquals(_tbl_SimSoDep_NguHanh, value))
                {
                    var previousValue = _tbl_SimSoDep_NguHanh;
                    _tbl_SimSoDep_NguHanh = value;
                    Fixuptbl_SimSoDep_NguHanh(previousValue);
                }
            }
        }
        private tbl_SimSoDep_NguHanh _tbl_SimSoDep_NguHanh;

        #endregion
        #region Association Fixup
    
        private void Fixuptbl_SimSoDep_NguHanh(tbl_SimSoDep_NguHanh previousValue)
        {
            if (previousValue != null && previousValue.tbl_SimSoDep_BanMenh.Contains(this))
            {
                previousValue.tbl_SimSoDep_BanMenh.Remove(this);
            }
    
            if (tbl_SimSoDep_NguHanh != null)
            {
                if (!tbl_SimSoDep_NguHanh.tbl_SimSoDep_BanMenh.Contains(this))
                {
                    tbl_SimSoDep_NguHanh.tbl_SimSoDep_BanMenh.Add(this);
                }
                if (IdNguHanh != tbl_SimSoDep_NguHanh.IdNguHanh)
                {
                    IdNguHanh = tbl_SimSoDep_NguHanh.IdNguHanh;
                }
            }
        }

        #endregion
    }
}
