//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace SimSoDepStore
{
    public partial class tbl_SimSoDep_SimSoLoaiSim
    {
        #region Primitive Properties
    
        public virtual int MaLoaiSim
        {
            get { return _maLoaiSim; }
            set
            {
                if (_maLoaiSim != value)
                {
                    if (tbl_SimSoDep_LoaiSim != null && tbl_SimSoDep_LoaiSim.MaLoaiSim != value)
                    {
                        tbl_SimSoDep_LoaiSim = null;
                    }
                    _maLoaiSim = value;
                }
            }
        }
        private int _maLoaiSim;
    
        public virtual long MaSoDienThoai
        {
            get { return _maSoDienThoai; }
            set
            {
                if (_maSoDienThoai != value)
                {
                    if (tbl_SimSoDep_SimSo != null && tbl_SimSoDep_SimSo.MaSoDienThoai != value)
                    {
                        tbl_SimSoDep_SimSo = null;
                    }
                    _maSoDienThoai = value;
                }
            }
        }
        private long _maSoDienThoai;
    
        public virtual Nullable<System.DateTime> CreateDate
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual tbl_SimSoDep_LoaiSim tbl_SimSoDep_LoaiSim
        {
            get { return _tbl_SimSoDep_LoaiSim; }
            set
            {
                if (!ReferenceEquals(_tbl_SimSoDep_LoaiSim, value))
                {
                    var previousValue = _tbl_SimSoDep_LoaiSim;
                    _tbl_SimSoDep_LoaiSim = value;
                    Fixuptbl_SimSoDep_LoaiSim(previousValue);
                }
            }
        }
        private tbl_SimSoDep_LoaiSim _tbl_SimSoDep_LoaiSim;
    
        public virtual tbl_SimSoDep_SimSo tbl_SimSoDep_SimSo
        {
            get { return _tbl_SimSoDep_SimSo; }
            set
            {
                if (!ReferenceEquals(_tbl_SimSoDep_SimSo, value))
                {
                    var previousValue = _tbl_SimSoDep_SimSo;
                    _tbl_SimSoDep_SimSo = value;
                    Fixuptbl_SimSoDep_SimSo(previousValue);
                }
            }
        }
        private tbl_SimSoDep_SimSo _tbl_SimSoDep_SimSo;

        #endregion
        #region Association Fixup
    
        private void Fixuptbl_SimSoDep_LoaiSim(tbl_SimSoDep_LoaiSim previousValue)
        {
            if (previousValue != null && previousValue.tbl_SimSoDep_SimSoLoaiSim.Contains(this))
            {
                previousValue.tbl_SimSoDep_SimSoLoaiSim.Remove(this);
            }
    
            if (tbl_SimSoDep_LoaiSim != null)
            {
                if (!tbl_SimSoDep_LoaiSim.tbl_SimSoDep_SimSoLoaiSim.Contains(this))
                {
                    tbl_SimSoDep_LoaiSim.tbl_SimSoDep_SimSoLoaiSim.Add(this);
                }
                if (MaLoaiSim != tbl_SimSoDep_LoaiSim.MaLoaiSim)
                {
                    MaLoaiSim = tbl_SimSoDep_LoaiSim.MaLoaiSim;
                }
            }
        }
    
        private void Fixuptbl_SimSoDep_SimSo(tbl_SimSoDep_SimSo previousValue)
        {
            if (previousValue != null && previousValue.tbl_SimSoDep_SimSoLoaiSim.Contains(this))
            {
                previousValue.tbl_SimSoDep_SimSoLoaiSim.Remove(this);
            }
    
            if (tbl_SimSoDep_SimSo != null)
            {
                if (!tbl_SimSoDep_SimSo.tbl_SimSoDep_SimSoLoaiSim.Contains(this))
                {
                    tbl_SimSoDep_SimSo.tbl_SimSoDep_SimSoLoaiSim.Add(this);
                }
                if (MaSoDienThoai != tbl_SimSoDep_SimSo.MaSoDienThoai)
                {
                    MaSoDienThoai = tbl_SimSoDep_SimSo.MaSoDienThoai;
                }
            }
        }

        #endregion
    }
}
