//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace SimSoDepStore
{
    public partial class tbl_SimSoDep_DaiLyTrietKhau
    {
        #region Primitive Properties
    
        public virtual int Id
        {
            get;
            set;
        }
    
        public virtual Nullable<long> GiaTu
        {
            get;
            set;
        }
    
        public virtual Nullable<long> Den
        {
            get;
            set;
        }
    
        public virtual Nullable<int> TrietKhau
        {
            get;
            set;
        }
    
        public virtual Nullable<int> MaDaiLy
        {
            get { return _maDaiLy; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_maDaiLy != value)
                    {
                        if (tbl_SimSoDep_DaiLy != null && tbl_SimSoDep_DaiLy.MaDaiLy != value)
                        {
                            tbl_SimSoDep_DaiLy = null;
                        }
                        _maDaiLy = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<int> _maDaiLy;

        #endregion
        #region Navigation Properties
    
        public virtual tbl_SimSoDep_DaiLy tbl_SimSoDep_DaiLy
        {
            get { return _tbl_SimSoDep_DaiLy; }
            set
            {
                if (!ReferenceEquals(_tbl_SimSoDep_DaiLy, value))
                {
                    var previousValue = _tbl_SimSoDep_DaiLy;
                    _tbl_SimSoDep_DaiLy = value;
                    Fixuptbl_SimSoDep_DaiLy(previousValue);
                }
            }
        }
        private tbl_SimSoDep_DaiLy _tbl_SimSoDep_DaiLy;

        #endregion
        #region Association Fixup
    
        private bool _settingFK = false;
    
        private void Fixuptbl_SimSoDep_DaiLy(tbl_SimSoDep_DaiLy previousValue)
        {
            if (previousValue != null && previousValue.tbl_SimSoDep_DaiLyTrietKhau.Contains(this))
            {
                previousValue.tbl_SimSoDep_DaiLyTrietKhau.Remove(this);
            }
    
            if (tbl_SimSoDep_DaiLy != null)
            {
                if (!tbl_SimSoDep_DaiLy.tbl_SimSoDep_DaiLyTrietKhau.Contains(this))
                {
                    tbl_SimSoDep_DaiLy.tbl_SimSoDep_DaiLyTrietKhau.Add(this);
                }
                if (MaDaiLy != tbl_SimSoDep_DaiLy.MaDaiLy)
                {
                    MaDaiLy = tbl_SimSoDep_DaiLy.MaDaiLy;
                }
            }
            else if (!_settingFK)
            {
                MaDaiLy = null;
            }
        }

        #endregion
    }
}
