//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace SimSoDepStore
{
    public partial class tbl_SimSoDep_DauSoChiTiet
    {
        #region Primitive Properties
    
        public virtual int MaDauSoChiTiet
        {
            get;
            set;
        }
    
        public virtual Nullable<int> MaDauSo
        {
            get { return _maDauSo; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_maDauSo != value)
                    {
                        if (tbl_SimSoDep_DauSo != null && tbl_SimSoDep_DauSo.MaDauSo != value)
                        {
                            tbl_SimSoDep_DauSo = null;
                        }
                        _maDauSo = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<int> _maDauSo;
    
        public virtual string TenDauSoChiTiet
        {
            get;
            set;
        }
    
        public virtual string MoTa
        {
            get;
            set;
        }
    
        public virtual string EnumFixed
        {
            get;
            set;
        }
    
        public virtual Nullable<int> MaNhaMang
        {
            get { return _maNhaMang; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_maNhaMang != value)
                    {
                        if (tbl_SimSoDep_NhaMang != null && tbl_SimSoDep_NhaMang.MaNhaMang != value)
                        {
                            tbl_SimSoDep_NhaMang = null;
                        }
                        _maNhaMang = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<int> _maNhaMang;
    
        public virtual Nullable<int> SapXep
        {
            get;
            set;
        }
    
        public virtual Nullable<int> Status
        {
            get;
            set;
        }
    
        public virtual string MetaDescription
        {
            get;
            set;
        }
    
        public virtual string MetaKeyword
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual tbl_SimSoDep_DauSo tbl_SimSoDep_DauSo
        {
            get { return _tbl_SimSoDep_DauSo; }
            set
            {
                if (!ReferenceEquals(_tbl_SimSoDep_DauSo, value))
                {
                    var previousValue = _tbl_SimSoDep_DauSo;
                    _tbl_SimSoDep_DauSo = value;
                    Fixuptbl_SimSoDep_DauSo(previousValue);
                }
            }
        }
        private tbl_SimSoDep_DauSo _tbl_SimSoDep_DauSo;
    
        public virtual ICollection<tbl_SimSoDep_SimSo> tbl_SimSoDep_SimSo
        {
            get
            {
                if (_tbl_SimSoDep_SimSo == null)
                {
                    var newCollection = new FixupCollection<tbl_SimSoDep_SimSo>();
                    newCollection.CollectionChanged += Fixuptbl_SimSoDep_SimSo;
                    _tbl_SimSoDep_SimSo = newCollection;
                }
                return _tbl_SimSoDep_SimSo;
            }
            set
            {
                if (!ReferenceEquals(_tbl_SimSoDep_SimSo, value))
                {
                    var previousValue = _tbl_SimSoDep_SimSo as FixupCollection<tbl_SimSoDep_SimSo>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= Fixuptbl_SimSoDep_SimSo;
                    }
                    _tbl_SimSoDep_SimSo = value;
                    var newValue = value as FixupCollection<tbl_SimSoDep_SimSo>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += Fixuptbl_SimSoDep_SimSo;
                    }
                }
            }
        }
        private ICollection<tbl_SimSoDep_SimSo> _tbl_SimSoDep_SimSo;
    
        public virtual tbl_SimSoDep_NhaMang tbl_SimSoDep_NhaMang
        {
            get { return _tbl_SimSoDep_NhaMang; }
            set
            {
                if (!ReferenceEquals(_tbl_SimSoDep_NhaMang, value))
                {
                    var previousValue = _tbl_SimSoDep_NhaMang;
                    _tbl_SimSoDep_NhaMang = value;
                    Fixuptbl_SimSoDep_NhaMang(previousValue);
                }
            }
        }
        private tbl_SimSoDep_NhaMang _tbl_SimSoDep_NhaMang;

        #endregion
        #region Association Fixup
    
        private bool _settingFK = false;
    
        private void Fixuptbl_SimSoDep_DauSo(tbl_SimSoDep_DauSo previousValue)
        {
            if (previousValue != null && previousValue.tbl_SimSoDep_DauSoChiTiet.Contains(this))
            {
                previousValue.tbl_SimSoDep_DauSoChiTiet.Remove(this);
            }
    
            if (tbl_SimSoDep_DauSo != null)
            {
                if (!tbl_SimSoDep_DauSo.tbl_SimSoDep_DauSoChiTiet.Contains(this))
                {
                    tbl_SimSoDep_DauSo.tbl_SimSoDep_DauSoChiTiet.Add(this);
                }
                if (MaDauSo != tbl_SimSoDep_DauSo.MaDauSo)
                {
                    MaDauSo = tbl_SimSoDep_DauSo.MaDauSo;
                }
            }
            else if (!_settingFK)
            {
                MaDauSo = null;
            }
        }
    
        private void Fixuptbl_SimSoDep_NhaMang(tbl_SimSoDep_NhaMang previousValue)
        {
            if (previousValue != null && previousValue.tbl_SimSoDep_DauSoChiTiet.Contains(this))
            {
                previousValue.tbl_SimSoDep_DauSoChiTiet.Remove(this);
            }
    
            if (tbl_SimSoDep_NhaMang != null)
            {
                if (!tbl_SimSoDep_NhaMang.tbl_SimSoDep_DauSoChiTiet.Contains(this))
                {
                    tbl_SimSoDep_NhaMang.tbl_SimSoDep_DauSoChiTiet.Add(this);
                }
                if (MaNhaMang != tbl_SimSoDep_NhaMang.MaNhaMang)
                {
                    MaNhaMang = tbl_SimSoDep_NhaMang.MaNhaMang;
                }
            }
            else if (!_settingFK)
            {
                MaNhaMang = null;
            }
        }
    
        private void Fixuptbl_SimSoDep_SimSo(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (tbl_SimSoDep_SimSo item in e.NewItems)
                {
                    item.tbl_SimSoDep_DauSoChiTiet = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (tbl_SimSoDep_SimSo item in e.OldItems)
                {
                    if (ReferenceEquals(item.tbl_SimSoDep_DauSoChiTiet, this))
                    {
                        item.tbl_SimSoDep_DauSoChiTiet = null;
                    }
                }
            }
        }

        #endregion
    }
}
