//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace SimSoDepStore
{
    public partial class tbl_SimSoDep_ClientIp
    {
        #region Primitive Properties
    
        public virtual long IdClientIp
        {
            get;
            set;
        }
    
        public virtual string IpAddress
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> ViewTime
        {
            get;
            set;
        }

        #endregion
    }
}
